##################################
#     VoidWarp-Limbo - Config    #
##################################

# yMin: The Y coordinate at the bottom of the range (Leave empty to have no minimum)
yMin: -1000
# yMax: The Y coordinate at the top of the range (Leave empty to have no maximum)
yMax: 0
# message: The message the player will see when moved from the region
message: "&7Teleported to &e%location%&7."